<?php  /** @var \Magento\Catalog\Model\Product $currentProduct */ ?>
<?php  /** @var \Plumrocket\OutOfStock\Block\ProductStockForm $block */ ?>

<?php if($block->getEnableModul()) :?>
    <?php if(!$block->getCurrentProduct()->isAvailable()) :?>
        <form id="out_of_stock_form" action="<?= $block->getUrl('outofstock/index/saveform') ?>" method="post" >
            <label for="email"><?= (__('Out of stock notification :'))?></label>
            <input type="email" name="email" placeholder="<?= (__('Add email for notification'))?>" id="email" class="out_of_stock_form__email">
            <input id="storeId" name="storeId" type="hidden" value="<?= $block->getStoreId()?>">
            <input id="productId" name="productId" type="hidden" value="<?= $block->getCurrentProduct()->getId()?>">
            <input type="submit" class="out_of_stock_form__button" value="<?= (__('Submit'))?>" >
        </form>
    <?php endif; ?>
<?php endif; ?>
<div id="result_form" ></div>
<script>
    require(['Plumrocket_OutOfStock/js/hello']);
</script>
