<?php
//$myBlock = \Magento\Framework\App\ObjectManager::getInstance()->get('Plumrocket\OutOfStock\Block\ProductStockForm');
/** @var \Magento\Catalog\Model\Product $currentProduct */


if ($currentProduct = $block->getCurrentProduct()) {

    var_dump($currentProduct->isAvailable());
}
?>
<form class="form subscribe"
      novalidate
      action="<?= $block->escapeUrl($block->getFormActionUrl()) ?>"
      method="post"
      data-mage-init='{"validation": {"errorClass": "mage-error"}}'
      id="newsletter-validate-detail">
    <div class="field newsletter">
        <div class="control">
            <label for="newsletter">
                        <span class="label">
                            <?= $block->escapeHtml(__('Sign Up for Our Newsletter:')) ?>
                        </span>
                <input name="email" type="email" id="newsletter"
                       placeholder="<?= $block->escapeHtml(__('Enter your email address')) ?>"
                       data-mage-init='{"mage/trim-input":{}}'
                       data-validate="{required:true, 'validate-email':true}"
                />
            </label>
        </div>
    </div>
    <div class="actions">
        <button class="action subscribe primary sr-only"
                title="<?= $block->escapeHtmlAttr(__('Subscribe')) ?>"
                type="submit"
                aria-label="Subscribe">
            <span><?= $block->escapeHtml(__('Subscribe')) ?></span>
        </button>
    </div>
</form>
